openapi: 3.0.3
info:
  title: EC Mall API
  description: ECモールサービスのAPIドキュメント
  version: 1.0.0
paths:
  /api/user/{userId}:
    get:
      operationId: getUserInfo
      summary: ユーザー情報取得
      description: ユーザー情報を取得する
      parameters:
        - name: userId
          in: path
          description: ユーザーID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    description: ユーザーID
                    type: string
                  name:
                    description: ユーザー名
                    type: string
                  age:
                    description: 年齢
                    type: number
        '404':
          description: Not Found.